name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * *
    - cron : 00 14 * * *
    - cron : 00 06 * * 1-5

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.1


      - name: Install nodejs and npm
        uses: actions/setup-node@v6.1.0
        with: 
          node-version: '22'

      - name: Install Newman and Html-extra-global
        run:  |
              npm install -g newman 
              npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run:  |
              newman run 'In Warranty Flow Collection.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra
        

          
